### PR TITLE
Issue number #1 fixing case sensitivity

### PR DESCRIPTION
**Pull request by RAJAGOPALAN-GANGADHARAN**

### CODE REVIEW

**Comment by RAJAGOPALAN-GANGADHARAN** [comment]
@bgadberr im not getting the specified warning u say can u help me to reproduce it

**Comment by RAJAGOPALAN-GANGADHARAN** [comment]
@bgadberr now check please

**Comment by bgadberr** [comment]
@RAJAGOPALAN-GANGADHARAN The issue is still occurring. I think it's because I'm using MacOS to run the script. Below is the result from terminal:

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/lightfm/_lightfm_fast.py:9: UserWarning: LightFM was compiled without OpenMP support. Only a single thread will be used.
  warnings.warn('LightFM was compiled without OpenMP support. '

I'm trying to ignore the UserWarning:

UserWarning: LightFM was compiled without OpenMP support. Only a single thread will be used.
  warnings.warn('LightFM was compiled without OpenMP support. '

Any ideas?

**Comment by RAJAGOPALAN-GANGADHARAN** [comment]
@bgadberr The code i changed also supposed to ignore the warnings.Maybe try to use -W flag while executing it

**Comment by bgadberr** [comment]
Thanks @RAJAGOPALAN-GANGADHARAN  . Looks like I needed to add the code before importing the LightFM module.

**Pull request closed without merging**
